# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170404_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(max_length=1),
        ),
    ]
