# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170405_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(choices=[('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly')], max_length=1),
        ),
    ]
